language: go

go: 1.6

notifications:
    email: false

env:
    - PATH=$HOME/gopath/bin:$PATH

install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/golang/lint/golint
    - go get -d -v ./... && go build -v ./...

script:
    - ./gok.sh
    - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash ./updatecov.sh; fi
