language: go
go:
    - 1.4
script: "./gok.sh"
install:
    - export PATH="$HOME/gopath/bin:$PATH"
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/golang/lint/golint
    - go get -d -v ./... && go build -v ./...
